# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink: /:year/:month/:day/:title/

# Setup
title:            Xiongkw's Blog
tagline:          'Xiongkw''s Blog'
description:      '据说明天有雨'
url:              http://xiongkw.github.io
baseurl:          /

author:
  name:           'Xiongkw'
  url:

# Custom vars
version:          2.1.0

github:
  repo:

# paginate
gems: [jekyll-paginate]
paginate: 5