# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink: /:year/:month/:day/:title/

# Setup
title:            Xiongkw's Blog
tagline:          'Xiongkw''s Blog'
description:      'This guy is too lazy for leaving nothing!'
url:              http://xiongkw.github.io
baseurl:          /

author:
  name:           'Xiongkw'
  url:

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:

# paginate
gems: [jekyll-paginate]
paginate: 6